apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec: # spec do deployment
  replicas: 1

  selector: # selector utilizado para criar o service
    matchLabels:
      app: mysql-server
      tier: db

  template: # referente ao POD
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec: # spec do POD
      containers:
      - name: mysql-server
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
